language: php

sudo: false

cache:
    directories:
        - vendor

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
    - PACKAGE_VERSION=high

matrix:
    include:
        - php: 5.3.3
          env: PACKAGE_VERSION=low

before_script:
    - composer selfupdate
    - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
    - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi

script:
    - echo '[phpspec] Running specification tests'; ./vendor/bin/phpspec run
    - echo '[phpunit] Running example tests'; ./vendor/bin/phpunit
